modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "areas_undefined"
version = "${version}"
displayName = "Areas Undefined"
authors = "ebo2022"
description = '''
Adds Regions Unexplored generation to vanilla biomes.
'''
#logoFile = ""

[[dependencies.areas_undefined]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.areas_undefined]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.areas_undefined]]
modId = "regions_unexplored"
mandatory = true
versionRange = "[0.4.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.areas_undefined]]
modId = "terrablender"
mandatory = true
versionRange = "[3.0.0.167,)"
ordering = "NONE"
side = "BOTH"