modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "areas_undefined"
version = "${version}"
displayName = "Areas Undefined"
authors = "ebo2022"
description = '''
Adds Regions Unexplored generation to vanilla biomes.
'''
#logoFile = ""

[[dependencies.areas_undefined]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.areas_undefined]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.areas_undefined]]
modId = "regions_unexplored"
mandatory = true
versionRange = "[0.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.areas_undefined]]
modId = "terrablender"
mandatory = true
versionRange = "[2.1.0.134,)"
ordering = "NONE"
side = "BOTH"